In [1]:
import torch
import torch.nn as nn
import torch.functional as F

In [2]:
# softmax + log + NLLLoss
x_input = torch.randn(3,3)
y_target = torch.tensor([1,2,0])
print('x_input:', x_input)
print('y_target:', y_target)

softmax = nn.Softmax()  # dim=1, default
output1 = torch.log(softmax(x_input))
print("log_softmax_output:", output1)
  
nllloss = nn.NLLLoss()   # 默认reduction = 'mean'
nllloss2 = nn.NLLLoss(reduction='none') 

output2 = nllloss(output1, y_target)
output22 = nllloss2(output1, y_target)
print("NLLLoss_output:", output2)
print(output22)

x_input: tensor([[-0.2678, -0.5112, -0.5859],
        [ 0.1939, -0.7122, -0.9426],
        [ 1.7665, -1.6362, -0.5112]])
y_target: tensor([1, 2, 0])
log_softmax_output: tensor([[-0.9209, -1.1643, -1.2390],
        [-0.5452, -1.4514, -1.6818],
        [-0.1273, -3.5300, -2.4050]])
NLLLoss_output: tensor(0.9911)
tensor([1.1643, 1.6818, 0.1273])


/home/xiang/anaconda3/envs/py37/lib/python3.7/site-packages/ipykernel_launcher.py:8: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  


In [3]:
# 直接使用CrossEntropyLoss()
a = torch.randn(3,3)
c = torch.tensor([1,2,0])
print(a)
print(c)
crossentropyloss = nn.CrossEntropyLoss()
output3 = crossentropyloss(x_input, y_target)
print("CrossEntropyLoss_output:", output3)
print(crossentropyloss(a, c))

tensor([[ 1.1054,  0.0897, -0.2460],
        [-0.5369, -1.8264,  0.6364],
        [-0.3799, -1.2077,  0.9826]])
tensor([1, 2, 0])
CrossEntropyLoss_output: tensor(0.9911)
tensor(1.1690)


In [ ]:
real = torch.tensor([[1/2],[1/4],[1/8],[1/8]])
pred = torch.tensor([[1/4],[1/4],[1/4],[1/4]])
print(real, pred)
print(crossentropyloss(real, pred))