In [2]:
import torch
import torch.nn as nn
import math

In [3]:
data=torch.FloatTensor([[1.0,2.0,3.0],[4.0,6.0,8.0]])
print(data)
print(data.shape)
print(data.type())

tensor([[1., 2., 3.],
        [4., 6., 8.]])
torch.Size([2, 3])
torch.FloatTensor


In [4]:
prob = nn.Softmax(dim=0)  # dim=0: tensor[0][?][?]
# dim = 0,在列上进行Softmax;dim=1,在行上进行Softmax
print(prob(data))
print(prob(data).shape)
print(prob(data).type())

tensor([[0.0474, 0.0180, 0.0067],
        [0.9526, 0.9820, 0.9933]])
torch.Size([2, 3])
torch.FloatTensor


In [5]:
print(math.exp(1)/(math.exp(1)+math.exp(4)))
print(math.exp(4)/(math.exp(1)+math.exp(4)))

0.04742587317756678
0.9525741268224331


In [6]:
# log-softmax就是再softmax上取对数
print(torch.log(prob(data)))

tensor([[-3.0486, -4.0181, -5.0067],
        [-0.0486, -0.0181, -0.0067]])
