In [20]:
import torch
import numpy as np
import torch.nn.functional as F

In [21]:
a = torch.randn((3,3))
print(a)

tensor([[ 0.3507,  1.6360, -0.8600],
        [ 1.2535,  0.3114,  0.2027],
        [-0.1764, -0.1767,  0.9981]])


In [22]:
b = torch.randn_like(a)
c = torch.zeros_like(a)
d = torch.ones_like(a)

print(b)
print(c)
print(d)

tensor([[ 0.6528,  0.9139,  1.0411],
        [ 0.4271,  0.2101,  2.4668],
        [-0.0987, -0.5280, -0.5401]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
F.adaptive_avg_pool2d()