In [175]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [176]:
inputs = torch.randn(1, 4, 481, 481)
inputs[0][3][3][3] = 1
x = torch.nonzero(inputs[0][3]==1)
print(x)

tensor([[3, 3]])


In [245]:
def crop_map(h, crop_size):
    
    bs, ch, H, W = h.size()
    print(h.size())
    
    map_tmp = torch.zeros(1, 4, H+crop_size, W+crop_size)
    map_c1 = torch.ones(H+crop_size, W+crop_size)
    map_tmp[0][0] = map_c1
   
    for i in range(ch):
        map_tmp[0][i][crop_size//2:crop_size//2+H, crop_size//2:crop_size//2+W] = h[0][i]
    
    x_pos = torch.nonzero(map_tmp[0][3]==1)[:][:,0][0]
    y_pos = torch.nonzero(map_tmp[0][3]==1)[:][:,1][0]
    
    # print(map_tmp)
    print("x_pos:{}, y_pos:{}".format(x_pos,y_pos))
    # print(map_tmp.size())
    # print(torch.nonzero(map_tmp[0][3]==1))
    
    output = torch.randn(1, 4, crop_size, crop_size)
    
    for i in range(ch):
        if crop_size%2 == 0:
            output[0][i] = map_tmp[0][i][x_pos-crop_size//2:x_pos+crop_size//2, y_pos-crop_size//2:y_pos+crop_size//2]
        else:
            output[0][i] = map_tmp[0][i][x_pos-crop_size//2:x_pos+crop_size//2+1, y_pos-crop_size//2:y_pos+crop_size//2+1]
            
    return output

In [246]:
inputs2 = torch.randn(1, 4, 6, 6)

inputs2[0][3][0][0] = 1
x = torch.nonzero(inputs2[0][3]==1)
print(x)
print(inputs2)
# print(inputs2)
crop_map(inputs2, 2)

tensor([[0, 0]])
tensor([[[[-0.7154, -0.3670,  0.8691, -0.2729,  0.3097, -0.2978],
          [-0.1253,  0.7683,  1.0625,  0.2669, -0.2179,  1.3899],
          [ 0.5671,  0.8810, -1.2941, -0.3305,  0.3114,  1.2983],
          [ 1.4531,  1.5239,  0.1792, -0.2327,  0.7347,  1.9757],
          [-0.0061, -1.3712, -0.4391,  0.6739, -0.8784, -0.1111],
          [ 0.1925,  2.3151, -0.5750, -0.0865, -0.2423, -0.3013]],

         [[ 0.3497, -0.0495, -0.9680, -0.2053, -1.5837,  1.4702],
          [ 0.6802, -1.5234,  0.8923,  0.5752,  0.8133, -0.4218],
          [ 1.2165, -0.3655, -0.1146,  0.7018,  1.7333, -1.4449],
          [ 0.7185,  0.5683, -0.2870,  0.0444, -0.6588, -1.1765],
          [-0.2449,  0.8808,  1.2814, -0.5984,  0.1579, -1.0759],
          [ 0.7661, -0.0743,  1.2667,  0.0809, -0.0230, -1.4319]],

         [[-0.3948,  1.0179, -0.9059,  0.1587, -0.2959,  0.3237],
          [-0.9392,  0.4071, -1.0105,  0.0394, -1.0898,  0.2789],
          [-1.1603,  1.1993,  1.7097,  0.4043, -1.8033,

tensor([[[[ 1.0000,  1.0000],
          [ 1.0000, -0.7154]],

         [[ 0.0000,  0.0000],
          [ 0.0000,  0.3497]],

         [[ 0.0000,  0.0000],
          [ 0.0000, -0.3948]],

         [[ 0.0000,  0.0000],
          [ 0.0000,  1.0000]]]])

In [244]:
a = torch.tensor([[2,3]])
b = torch.randn(10,10)
print(a)
print(a.size())
print(torch.unsqueeze(a, 2))
print(a)
print(a[:][:,0][0] + a[:][:,1][0])
print(b[a[:][:,0][0]][a[:][:,1][0]])

tensor([[2, 3]])
torch.Size([1, 2])
tensor([[[2],
         [3]]])
tensor([[2, 3]])
tensor(5)
tensor(-0.8993)


In [95]:
a = torch.randn((5,5))
print(a[3][3])
print(a)
print("---"*3)
print(a[3-1:3+2, 3-1:3+2])

tensor(-1.0409)
tensor([[-0.2100,  0.5048,  0.1150, -1.3764, -0.0068],
        [-0.1414,  0.7513,  0.5066, -0.5157, -1.1068],
        [-1.2784,  1.2264, -0.4960,  2.4908,  0.5956],
        [-0.8810,  0.1898,  1.3371, -1.0409, -1.0964],
        [ 0.9607, -0.9174, -0.6322,  0.3216,  0.6967]])
---------
tensor([[-0.4960,  2.4908,  0.5956],
        [ 1.3371, -1.0409, -1.0964],
        [-0.6322,  0.3216,  0.6967]])


In [125]:
a = torch.tensor([1,2,3])
print(a[0])
print(a[0].numpy())

tensor(1)
1
