In [2]:
import torch
from torch.autograd import Variable

In [27]:
# gradient for scalar
x = Variable(torch.Tensor([2,3]), requires_grad=True)  # tensor([2., 3.], requires_grad=True)
x1 = x + 3  # tensor([5., 6.], grad_fn=<AddBackward0>)
x2 = x1*x1*3 # 同上
y = x2.mean()  #tensor(91.5000, grad_fn=<MeanBackward0>)

# print(y.data)   # tensor(91.5000)
print(x.data)  #tensor([2., 3.])
print(x.grad)  # None
y.backward()
print(x.grad)  #tensor([15., 18.])

tensor([2., 3.])
None
tensor([15., 18.])


In [5]:
# gradient for vectors
m = Variable(torch.Tensor([[2,3]]), requires_grad=True)
n = Variable(torch.zeros(1,2))
v = Variable(torch.zeros(1,2))
n[0,0] = m[0,0]**2
n[0,1] = m[0,1]**3
v[0,0] = m[0,0]**2 + m[0,1]**2
v[0,1] = m[0,0]**3 + m[0,1]**3

# n.backward(torch.Tensor([[0,1]]))
v.backward(torch.Tensor([[2,0.5]]))  
#此处的系数是，因变量（结果）两个结果分别对x1和x2求导完后的系数:
# 比如上面 v[k1,k2], 这里求导是对X1：求导（k1/x1）+求导(k2/x1)。然后backward的系数是k1和k2的系数
print('*' * 10)
print('==== non scalar output ======')
print('input')
print(m.data)
print('input gradient are')
print(m.grad.data)

**********
==== non scalar output ======
input
tensor([[2., 3.]])
input gradient are
tensor([[14.0000, 25.5000]])


In [25]:
input = torch.ones([2, 2], requires_grad=False)
w1 = torch.tensor(2.0, requires_grad=True)
w2 = torch.tensor(3.0, requires_grad=True)
w3 = torch.tensor(4.0, requires_grad=True)
l1 = input * w1
l2 = l1 + w2
l3 = l1 * w3
l4 = l2 * l3
loss = l4.mean()

# 反向传播前
print(w1.data, w1.grad, w1.grad_fn)  # tensor(2.) None None
print(l1.data, l1.grad, l1.grad_fn)   # tensor([[2., 2.],[2., 2.]]) None <MulBackward0 object at 0x000001EBE79E6AC8>
print(loss.data, loss.grad, loss.grad_fn)  # tensor(40.) None <MeanBackward0 object at 0x000001EBE79D8208>
print(l2.data, l2.grad, l2.grad_fn)  #tensor([[5., 5.],[5., 5.]]) None <AddBackward0 object at 0x7fca426aba50>
print(l3.data, l3.grad, l3.grad_fn) # 8 8 8 8  None <MulBackward0 object at 0x7fca42b83bd0>
print(l4.data, l4.grad, l4.grad_fn)   # 40 40 40 40  None <MulBackward0 object at 0x7fca426aba50>
print(input.data, input.grad, input.grad_fn)   # tensor([[1., 1.],[1., 1.]]) None None

# 反向传播后（求导后）
loss.backward()
print(w1.data, w1.grad, w1.grad_fn)  # tensor(2.) tensor(28.) None
print(l1.data, l1.grad, l1.grad_fn)   # tensor([[2., 2.],[2., 2.]]) None <MulBackward0 object at 0x000001EBE79E6AC8>
print(loss.data, loss.grad, loss.grad_fn)  # tensor(40.) None <MeanBackward0 object at 0x000001EBE79D8208>
print(l2.data, l2.grad, l2.grad_fn)  #tensor([[5., 5.],[5., 5.]]) None <AddBackward0 object at 0x7fca426aba50>
print(l3.data, l3.grad, l3.grad_fn) # 8 8 8 8  None <MulBackward0 object at 0x7fca42b83bd0>
print(l4.data, l4.grad, l4.grad_fn)   # 40 40 40 40  None <MulBackward0 object at 0x7fca426aba50>
print(input.data, input.grad, input.grad_fn)   # tensor([[1., 1.],[1., 1.]]) None None

tensor(2.) None None
tensor([[2., 2.],
        [2., 2.]]) None <MulBackward0 object at 0x7faa83fec6d0>
tensor(40.) None <MeanBackward0 object at 0x7fa9d1af9090>
tensor([[5., 5.],
        [5., 5.]]) None <AddBackward0 object at 0x7faa83fec6d0>
tensor([[8., 8.],
        [8., 8.]]) None <MulBackward0 object at 0x7fa9d1af9090>
tensor([[40., 40.],
        [40., 40.]]) None <MulBackward0 object at 0x7faa83fec6d0>
tensor([[1., 1.],
        [1., 1.]]) None None
tensor(2.) tensor(28.) None
tensor([[2., 2.],
        [2., 2.]]) None <MulBackward0 object at 0x7faa83fec6d0>
tensor(40.) None <MeanBackward0 object at 0x7fa9cb2d0d90>
tensor([[5., 5.],
        [5., 5.]]) None <AddBackward0 object at 0x7faa83fec6d0>
tensor([[8., 8.],
        [8., 8.]]) None <MulBackward0 object at 0x7fa9cb2d0d90>
tensor([[40., 40.],
        [40., 40.]]) None <MulBackward0 object at 0x7faa83fec6d0>
tensor([[1., 1.],
        [1., 1.]]) None None


/home/xiang/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/ipykernel_launcher.py:12: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information.
  if sys.path[0] == '':
/home/xiang/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/ipykernel_launcher.py:13: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/p

In [26]:
print(w1.is_leaf)   # True
print(input.is_leaf)   # True
print(l1.is_leaf)   # False

True
True
False
