In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import time
import gym
import numpy
import onnx
import onnxruntime
from gym import wrappers
import os
from typing import Any, Dict, List, Optional
import glob
# from base.rl.ppo import PPO

In [2]:
pthfile = 'ckpt.test.pth'
onnxpath = 'test_conv_pool.onnx'
print(torch.__version__)
print(onnx.__version__)
print(onnxruntime.__version__)

1.2.0
1.6.0
1.6.0


In [3]:
def crop_map(h, crop_size):
    
#     bs = torch.tensor(1)
#     ch = torch.tensor(4)
#     H = torch.tensor(481)
#     W = torch.tensor(481)
    
    tmp_h_0 = torch.zeros(120, 481)
    tmp_h_1 = torch.ones(120, 481)
    tmp_v_0 = torch.zeros(721, 120)
    tmp_v_1 = torch.ones(721, 120)
    
    ############### first map ######################
    tmp_map = h
    # print("h size::", h.size())
    
    tmp_h0 = torch.cat((tmp_map[0][0], tmp_h_1), dim=0)
    tmp_h0 = torch.cat((tmp_h_1, tmp_h0), dim=0)
    # print("tmp_h:", tmp_h.size())

    tmp_v0 = torch.cat((tmp_h0, tmp_v_1), dim=1)
    tmp_v0 = torch.cat((tmp_v_1, tmp_v0), dim=1)
    
    ################ second map ####################
    tmp_map = h
    # print("h size::", h.size())
    
    tmp_h1 = torch.cat((tmp_map[0][1], tmp_h_0), dim=0)
    tmp_h1 = torch.cat((tmp_h_0, tmp_h1), dim=0)
    # print("tmp_h:", tmp_h.size())

    tmp_v1 = torch.cat((tmp_h1, tmp_v_0), dim=1)
    tmp_v1 = torch.cat((tmp_v_0, tmp_v1), dim=1)

    ################ Third map ####################
    tmp_map = h
    # print("h size::", h.size())
    
    tmp_h2 = torch.cat((tmp_map[0][2], tmp_h_0), dim=0)
    tmp_h2 = torch.cat((tmp_h_0, tmp_h2), dim=0)
    # print("tmp_h:", tmp_h.size())

    tmp_v2 = torch.cat((tmp_h2, tmp_v_0), dim=1)
    tmp_v2 = torch.cat((tmp_v_0, tmp_v2), dim=1)
    # print("tmp_v:", tmp_v.size())

    ################ Forth map ####################

    # tensor_index = torch.linspace(120., 601., 481)
    tmp_map = h
    # print("h size::", h.size())
    
    tmp_h3 = torch.cat((tmp_map[0][3], tmp_h_0), dim=0)
    tmp_h3 = torch.cat((tmp_h_0, tmp_h3), dim=0)
    # print("tmp_h:", tmp_h.size())

    tmp_v3 = torch.cat((tmp_h3, tmp_v_0), dim=1)
    tmp_v3 = torch.cat((tmp_v_0, tmp_v3), dim=1)
    
    ################################################
    map_tmp = torch.cat((torch.unsqueeze(tmp_v0, 0), torch.unsqueeze(tmp_v1, 0), 
                         torch.unsqueeze(tmp_v2, 0), torch.unsqueeze(tmp_v3, 0)), 0)
    map_tmp = torch.unsqueeze(map_tmp, 0)
    # print("after expanding map size:", map_tmp.size())

    ############ start crap map #####################
    x_pos = torch.nonzero(map_tmp[0][3]==1)[:][:,0][0]
    y_pos = torch.nonzero(map_tmp[0][3]==1)[:][:,1][0]
    
    
    # print(map_tmp)
    # print("x_pos:{}, y_pos:{}".format(x_pos,y_pos))
    # print(map_tmp.size())
    # print(torch.nonzero(map_tmp[0][3]==1))
    index_tensor = torch.linspace(-120, 119, 240)
    # index_tensor = torch.tensor([-120, -119, -118, -117, -116, -115, -114, -113, -112, -111, -110, -109, -108, -107, -106, -105, -104, -103, -102, -101, -100, -99, -98, -97, -96, -95, -94, -93, -92, -91, -90, -89, -88, -87, -86, -85, -84, -83, -82, -81, -80, -79, -78, -77, -76, -75, -74, -73, -72, -71, -70, -69, -68, -67, -66, -65, -64, -63, -62, -61, -60, -59, -58, -57, -56, -55, -54, -53, -52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39, -38, -37, -36, -35, -34, -33, -32, -31, -30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119])
    # index_tensor = index_tensor.long()
    index_tensor_x = index_tensor.long() + x_pos.long()
    index_tensor_y = index_tensor.long() + y_pos.long()
    # print("index_tensor_x", index_tensor_x)

    tmp_crap_map_0 = torch.index_select(map_tmp[0][0], 1, index_tensor_y)
    tmp_crap_map_0 = torch.index_select(tmp_crap_map_0, 0, index_tensor_x)
    
    tmp_crap_map_1 = torch.index_select(map_tmp[0][1], 1, index_tensor_y)
    tmp_crap_map_1 = torch.index_select(tmp_crap_map_1, 0, index_tensor_x)
    
    tmp_crap_map_2 = torch.index_select(map_tmp[0][2], 1, index_tensor_y)
    tmp_crap_map_2 = torch.index_select(tmp_crap_map_2, 0, index_tensor_x)
    
    tmp_crap_map_3 = torch.index_select(map_tmp[0][3], 1, index_tensor_y)
    tmp_crap_map_3 = torch.index_select(tmp_crap_map_3, 0, index_tensor_x)
    
    tmp = tmp_crap_map_3
    
    '''
    output = torch.cat((torch.unsqueeze(tmp_crap_map_0, 0), torch.unsqueeze(tmp_crap_map_1, 0),
                       torch.unsqueeze(tmp_crap_map_2, 0), torch.unsqueeze(tmp_crap_map_3, 0)), 0)
    output = torch.unsqueeze(output, 0)
    # print("ouput::::",output.size())
    '''
    # output = torch.randn(1, 4, crop_size, crop_size)
    '''
    output[0][0] = tmp_crap_map_0
    output[0][1] = tmp_crap_map_1
    output[0][2] = tmp_crap_map_2
    output[0][3] = tmp_crap_map_3
    '''
    
    tmp_0 = tmp_crap_map_0
    tmp_1 = tmp_crap_map_1
    tmp_2 = tmp_crap_map_2
    tmp_3 = tmp_crap_map_3
    tmp_0 = torch.reshape(tmp_0,[1,1,tmp_0.shape[0],tmp_0.shape[1]])
    tmp_1 = torch.reshape(tmp_1,[1,1,tmp_1.shape[0],tmp_1.shape[1]])
    tmp_2 = torch.reshape(tmp_2,[1,1,tmp_2.shape[0],tmp_2.shape[1]])
    tmp_3 = torch.reshape(tmp_3,[1,1,tmp_3.shape[0],tmp_3.shape[1]])
    
    tmp = torch.cat((tmp_0,tmp_1,tmp_2,tmp_3),1)
#     tmp_0 = torch.unsqueeze(tmp_crap_map_0, 0)
#     tmp_1 = torch.unsqueeze(tmp_crap_map_1, 0)
#     tmp_2 = torch.unsqueeze(tmp_crap_map_2, 0)
#     tmp_3 = torch.unsqueeze(tmp_crap_map_3, 0)
    
#     tmp = torch.cat((tmp_0, tmp_1), 0)
#     tmp = torch.cat((tmp, tmp_2), 0)
#     tmp = torch.cat((tmp, tmp_3), 0)
#     tmp = torch.unsqueeze(tmp, 0)
    # print("tmp size:", tmp.size())
    
    # tmp = torch.index_select(tmp, 0, torch.tensor([0]))
    # print("tmp size:", tmp.size())
    # output = tmp
    # print("output:", tmp.size())
    
    
    return tmp

class Flatten(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        return x.view(x.shape[0], -1)

class Global_Actor(nn.Module):
    def __init__(self, G):
        super().__init__()
        self.G = torch.tensor(G)
        self.actor = nn.Sequential(  # (8, G, G)
            nn.Conv2d(8, 8, 3, padding=1),  # (8, G, G)
            nn.BatchNorm2d(8),
            nn.ReLU(),
            nn.Conv2d(8, 4, 3, padding=1),  # (4, G, G)
            nn.BatchNorm2d(4),
            nn.ReLU(),
            nn.Conv2d(4, 4, 5, padding=2),  # (4, G, G)
            nn.BatchNorm2d(4),
            nn.ReLU(),
            nn.Conv2d(4, 2, 5, padding=2),  # (2, G, G)
            nn.BatchNorm2d(2),
            nn.ReLU(),
            nn.Conv2d(2, 1, 5, padding=2),  # (1, G, G)
            Flatten(),  # (G*G, )
            nn.Sigmoid(),  # added for non-negative
        )
        
        
    def _get_h12(self, inputs): # inputs needs to be a tensor, i.e., original inputs["map_at_t"], (bs, 4, M, M), channel 3 means one-hot pose, channel 0~1 means global map
        # x = inputs["pose_in_map_at_t"]  # (bs,2)
        # map_at_t (4, m, m)
        # x = torch.nonzero(inputs[0][3]==1)
        h = inputs
        
        h_1 = crop_map(h, self.G)
        # print(torch.nonzero(h_1[0][3]==1))
        h_2 = F.max_pool2d(h, (2, 2))
# adaptive_max_pool2d
        #print("h111:", h_1.size())
        #print("h22:", h_2.size())
    
        h_12 = torch.cat((h_1, h_2), dim=1)

        return h_12

    def forward(self, inputs):
        x1 = self._get_h12(inputs)
        x2 = self.actor(x1)
        return x2

In [4]:
actor_net = Global_Actor(240)
actor_net.actor.load_state_dict(torch.load(pthfile, map_location='cpu'),strict=False)
    # Initialize model with the pretrained weights

_IncompatibleKeys(missing_keys=['0.weight', '0.bias', '1.weight', '1.bias', '1.running_mean', '1.running_var', '3.weight', '3.bias', '4.weight', '4.bias', '4.running_mean', '4.running_var', '6.weight', '6.bias', '7.weight', '7.bias', '7.running_mean', '7.running_var', '9.weight', '9.bias', '10.weight', '10.bias', '10.running_mean', '10.running_var', '12.weight', '12.bias'], unexpected_keys=['global_state_dict', 'extra_state'])

In [5]:
inputs = torch.randn(1, 4, 481, 481)

map3 = torch.zeros(1, 481, 481)
map3[0][20][20] = 1.
inputs[0][3] = map3
'''
print(map3)
print(torch.nonzero(map3==1))
inputs[0][3] = map3 'tensor(flo
yy = torch.nonzero(inputs[0][3]==1)
print(type(yy))
print(type(yy[:,:2]))
print(yy == yy[:,:2])
print(x.size())
'''

x = inputs

In [14]:
def test():
    M = 481
    model = Global_Actor(240)
    batch_size = 1
    input_shape = (4, M, M)
    
    # Initialize model with the pretrained weights
    # map_location = 'gpu' if torch.cuda.is_available() else 'cpu'
    loaded_model = torch.load(pthfile, map_location="cpu")
    model.actor.load_state_dict(loaded_model, strict=False)
    
    # set the model to inference mode
    model.eval()
    
    # data type nchw
    # x = torch.rand(batch_size, *input_shape)

    # # Export the model
    torch.onnx.export(model, x, 
                      onnxpath, 
                      opset_version=10)
                      #keep_initializers_as_inputs=True, 
                      # verbose=True
    '''
    torch.onnx.export(model,               # model being run
                    x,                         # model input (or a tuple for multiple inputs)
                    onnxpath,   # where to save the model (can be a file or file-like object)
                    export_params=True,        # store the trained parameter weights inside the model file
                    opset_version=10,          # the ONNX version to export the model to
                    do_constant_folding=True,  # whether to execute constant folding for optimization
                    input_names = ['input'],   # the model's input names
                    output_names = ['output'], # the model's output names
                    dynamic_axes={'input' : {0 : 'batch_size'},    # variable lenght axes
                                  'output' : {0 : 'batch_size'}}
                     )
    '''
    print("=============Successful==========")

In [15]:
test()

=============Successful==========


In [8]:
a = torch.randn(1,3,2,2)
b = torch.randn(1,1,2,2)
print(a)
print(b)
c = torch.cat((a,b),dim=1)
print(c)
print(c.size())

tensor([[[[-1.2478, -1.2804],
          [ 1.0480, -0.0234]],

         [[ 0.2194,  0.7509],
          [-0.2113,  0.3923]],

         [[ 1.0334,  0.2553],
          [ 0.7283, -1.0217]]]])
tensor([[[[-1.5599, -0.2362],
          [-1.1376,  1.0681]]]])
tensor([[[[-1.2478, -1.2804],
          [ 1.0480, -0.0234]],

         [[ 0.2194,  0.7509],
          [-0.2113,  0.3923]],

         [[ 1.0334,  0.2553],
          [ 0.7283, -1.0217]],

         [[-1.5599, -0.2362],
          [-1.1376,  1.0681]]]])
torch.Size([1, 4, 2, 2])


In [308]:
a = torch.zeros(1,1,2,2)
print(a)
b = torch.ones(1,2)
print(a[0][0].size())
print(a[0][0])
print(b)
tmp = torch.cat((a[0][0], b), dim=0)
print("-------------------")
print(tmp)
tmp = torch.cat((b, tmp), dim=0)
print(tmp)
a = torch.cat((b, a[0][0]), dim=0)
print(a)

tensor([[[[0., 0.],
          [0., 0.]]]])
torch.Size([2, 2])
tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.]])
-------------------
tensor([[0., 0.],
        [0., 0.],
        [1., 1.]])
tensor([[1., 1.],
        [0., 0.],
        [0., 0.],
        [1., 1.]])
tensor([[1., 1.],
        [0., 0.],
        [0., 0.]])


In [ ]:
    torch.onnx.export(model,               # model being run
                    x,                         # model input (or a tuple for multiple inputs)
                    onnxpath,   # where to save the model (can be a file or file-like object)
                    export_params=True,        # store the trained parameter weights inside the model file
                    opset_version=10,          # the ONNX version to export the model to
                    do_constant_folding=True,  # whether to execute constant folding for optimization
                    input_names = ['input'],   # the model's input names
                    output_names = ['output'], # the model's output names
                    dynamic_axes={'input' : {0 : 'batch_size'},    # variable lenght axes
                                  'output' : {0 : 'batch_size'}}
                     )