In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
inputs = torch.randn(1, 4, 481, 481)
inputs[0][3][3][3] = 1
x = torch.nonzero(inputs[0][3]==1)
print(x)

tensor([[3, 3]])


In [15]:
def crop_map(h, crop_size):
    
    bs, ch, H, W = h.size()
    print(h.size())
    
    map_tmp = torch.zeros(1, 4, H+crop_size, W+crop_size)
    map_c1 = torch.ones(H+crop_size, W+crop_size)
    map_tmp[0][0] = map_c1
   
    for i in range(ch):
        map_tmp[0][i][crop_size//2:crop_size//2+H, crop_size//2:crop_size//2+W] = h[0][i]
    
    x_pos = torch.nonzero(map_tmp[0][3]==1)[:][:,0][0]
    y_pos = torch.nonzero(map_tmp[0][3]==1)[:][:,1][0]
    print("x_pos:", x_pos)
    # print(map_tmp)
    print("x_pos:{}, y_pos:{}".format(x_pos,y_pos))
    print(type(y_pos))
    # print(map_tmp.size())
    # print(torch.nonzero(map_tmp[0][3]==1))
    
    output = torch.randn(1, 4, crop_size, crop_size)
    print("x_pos-crop_size//2:x_pos+crop_size//2:", x_pos-crop_size//2)
    for i in range(ch):
        if crop_size%2 == 0:
            output[0][i] = map_tmp[0][i][x_pos-crop_size//2:x_pos+crop_size//2, y_pos-crop_size//2:y_pos+crop_size//2]
        else:
            output[0][i] = map_tmp[0][i][x_pos-crop_size//2:x_pos+crop_size//2+1, y_pos-crop_size//2:y_pos+crop_size//2+1]
            
    return output

In [16]:
inputs2 = torch.randn(1, 4, 6, 6)

inputs2[0][3][0][0] = 1
x = torch.nonzero(inputs2[0][3]==1)
print(x)
print(inputs2)
# print(inputs2)
crop_map(inputs2, 2)

tensor([[0, 0]])
tensor([[[[ 1.0152,  0.9502, -0.5721,  0.9429,  1.8131,  0.3201],
          [ 0.0832, -1.2330,  1.8328, -1.6603,  0.4157, -1.7857],
          [-0.4274, -0.5448, -0.3152,  0.2619, -1.2369,  0.1625],
          [ 0.2658,  0.6412, -0.5335, -0.3450,  0.7805, -0.8096],
          [ 0.9514,  1.9749,  0.3116, -0.5790, -0.3669,  1.4854],
          [-0.3704,  0.3333, -0.6485,  0.5441,  1.4294, -0.5217]],

         [[ 1.9797, -1.0624,  0.4209, -1.8423,  0.6186,  0.0981],
          [-1.9849, -0.6857,  0.4291,  1.7524, -0.4056,  1.6470],
          [ 1.4825, -0.1919, -0.2294, -0.3798,  0.4144, -0.7280],
          [ 0.5650, -2.0395, -1.2648,  0.6714,  0.2187,  0.3129],
          [-1.3115,  2.0814, -0.6310, -0.3745,  0.7805, -0.2673],
          [-0.2774, -0.0758, -0.2359,  0.5439, -1.0801, -2.1026]],

         [[-0.9457, -0.4126,  0.0227,  0.2388, -1.3501, -0.5433],
          [-0.3973,  0.7479,  1.1237, -0.3419, -0.6054, -0.2797],
          [-2.1882,  0.4362, -0.4509, -0.8906, -0.1936,

tensor([[[[ 1.0000,  1.0000],
          [ 1.0000,  1.0152]],

         [[ 0.0000,  0.0000],
          [ 0.0000,  1.9797]],

         [[ 0.0000,  0.0000],
          [ 0.0000, -0.9457]],

         [[ 0.0000,  0.0000],
          [ 0.0000,  1.0000]]]])

In [17]:
a = torch.tensor([[2,3]])
b = torch.randn(10,10)
print(a)
print(a.size())
print(torch.unsqueeze(a, 2))
print(a)
print(a[:][:,0][0] + a[:][:,1][0])
print(b[a[:][:,0][0]][a[:][:,1][0]])

tensor([[2, 3]])
torch.Size([1, 2])
tensor([[[2],
         [3]]])
tensor([[2, 3]])
tensor(5)
tensor(1.8849)


In [95]:
a = torch.randn((5,5))
print(a[3][3])
print(a)
print("---"*3)
print(a[3-1:3+2, 3-1:3+2])

tensor(-1.0409)
tensor([[-0.2100,  0.5048,  0.1150, -1.3764, -0.0068],
        [-0.1414,  0.7513,  0.5066, -0.5157, -1.1068],
        [-1.2784,  1.2264, -0.4960,  2.4908,  0.5956],
        [-0.8810,  0.1898,  1.3371, -1.0409, -1.0964],
        [ 0.9607, -0.9174, -0.6322,  0.3216,  0.6967]])
---------
tensor([[-0.4960,  2.4908,  0.5956],
        [ 1.3371, -1.0409, -1.0964],
        [-0.6322,  0.3216,  0.6967]])


In [125]:
a = torch.tensor([1,2,3])
print(a[0])
print(a[0].numpy())

tensor(1)
1


In [18]:
a = torch.tensor(1)
print(a)
print(type(a))

tensor(1)
<class 'torch.Tensor'>
