In [21]:
import torch
import torch.nn as nn
import math

In [14]:
a = torch.tensor([1.,2.,3.], requires_grad=True)

In [27]:
print(a)
print(a.data)
print(type(a.data))
print(a.requires_grad)

tensor([1., 2., 3.], requires_grad=True)
tensor([1., 2., 3.])
<class 'torch.Tensor'>
True


In [28]:
c = a.data
print(c)
c = torch.tensor([1.,1.,1.])
print(c)
print(a)
print(c.requires_grad)

tensor([1., 2., 3.])
tensor([1., 1., 1.])
tensor([1., 2., 3.], requires_grad=True)
False


In [29]:
d = a.detach()
print(d)
d = torch.tensor([2.,2.,2.])
print(d)
print(a)
print(d.requires_grad)

tensor([1., 2., 3.])
tensor([2., 2., 2.])
tensor([1., 2., 3.], requires_grad=True)
False


In [19]:
soft = nn.Softmax()
sigm = nn.Sigmoid()

In [23]:
print(a)
print(soft(a))
print(sigm(a))
print(math.exp(1)/(math.exp(1)+math.exp(2)+math.exp(3)))

tensor([1., 2., 3.], requires_grad=True)
tensor([0.0900, 0.2447, 0.6652], grad_fn=<SoftmaxBackward>)
tensor([0.7311, 0.8808, 0.9526], grad_fn=<SigmoidBackward>)
0.09003057317038046


/home/xiang/anaconda3/envs/py37/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  


In [34]:
a = torch.tensor([1, 2, 3.], requires_grad=True)
print(a)
out = a.tanh()
print(out)

# 需要走注意的是，通过.data “分离”得到的的变量会和原来的变量共用同样的数据
# 而且新分离得到的张量是不可求导的，c发生了变化，原来的张量也会发生变化
c = out.data
c.zero_() # 改变c的值，原来的out也会改变
print(c.requires_grad)
print("c：", c)
print(out.requires_grad)
print(out)
print("----------------------------------------------")
 
out.sum().backward()  # 对原来的out求导，
print(a.grad)  # 不会报错，但是结果却并不正确

tensor([1., 2., 3.], requires_grad=True)
tensor([0.7616, 0.9640, 0.9951], grad_fn=<TanhBackward>)
False
c： tensor([0., 0., 0.])
True
tensor([0., 0., 0.], grad_fn=<TanhBackward>)
----------------------------------------------
tensor([1., 1., 1.])


In [40]:
a = torch.tensor([1, 2, 3.], requires_grad=True)
print(a)
out = a.tanh()
print(out)

# 需要走注意的是，通过.detach() “分离”得到的的变量会和原来的变量共用同样的数据
# 而且新分离得到的张量是不可求导的，c发生了变化，原来的张量也会发生变化
c = out.detach()  
c.zero_()  # 改变c的值，原来的out也会改变
print(c.requires_grad)
print("c:",c)
print(out.requires_grad)
print(out)
print("----------------------------------------------")
 
out.sum().backward()  # 对原来的out求导，
# 此时会报错，错误结果参考下面,显示梯度计算所需要的张量已经被“原位操作inplace”所更改了。
print(a.grad)

tensor([1., 2., 3.], requires_grad=True)
tensor([0.7616, 0.9640, 0.9951], grad_fn=<TanhBackward>)
False
c: tensor([0., 0., 0.])
True
tensor([0., 0., 0.], grad_fn=<TanhBackward>)
----------------------------------------------


RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [3]], which is output 0 of TanhBackward, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).