In [2]:
import torch, numpy

In [4]:
# cat 和 stack 都是多个tensors（只能是tensors）合并。tensors以一个list形式送进去
# 每个tensors的shape必须一样，比如N个（a，b，c）的tensors合并
# cat不会改变原来tesnors的shape，比如上面三维，N个tensors合并
    # 那么dim只有0，1，2三种情况。0对应第一维的改变：（a*N，b，c）
    # 同理第二维：（a，b*N，c）
# stack会在原来tensors的shape上加一为维度，类似unsqueeze插值
    # 上述例子（a，b，c）。dim = 0对应N插在第一位（N，a，b，c）
    # 其余同理。所以这里dim可以为0，1，2，3

x1 = numpy.array([[1,2,3],
                  [2,3,4]])
x2 = numpy.array([[6,7,8],
                  [11,12,13]])

In [13]:
print("x1.shape = ", x1.shape)
print("x2.shape = ", x2.shape)

x3 = numpy.array([x1, x2])
print("x3.shape = ", x3.shape)


# tensors -> arrays = Var.numpy().  arrays —> tensors = torch.from_numpy(Var)
x4 = torch.from_numpy(x1)
x5 = torch.from_numpy(x2)
x6 = torch.from_numpy(x3)
print(torch.unsqueeze(x6, dim=0).size())
x7 = [x4, x5]
print("--------------numpy初始化数据规律------------")
x9 = numpy.array(numpy.array([[2]]))
print(type(x9))
print(type(x9[0]))
print(type(x9[0][0]))
print("-----------------tensor初始化数据规律------------")
x10 = torch.tensor([[1,2],[2,3]])
print(type(x10))
print(type(x10[0]))
print(x10[0])
print(type(x10[0][0]))
print("可看出numpy创建数组，最外层类型就算array，最小单位还是int")
print("但是用tensor创建tensor类型，从里到外所有数据类型都属于tensor")

x11 = [x1, x2]  # list中两个类型一样：array，array
x12 = [x2, x4]  # list中两个类型不一样 array，tensor 
x13 = [x4, x5]   # # list中两个类型一样 tensor，tensor
print(x10)
print("list中两个类型一样：array，array:\n", x11)
print("list中两个类型不一样 array，tensor:\n", x12)
print("list中两个类型一样 tensor，tensor:\n", x13)
'''
a = torch.tensor(x11)
print(a)
print(a[0])
print([a[0][0]])
b = torch.tensor(x12)
print(b)   # a 和 b都成功被转换为了tensor，从里到外：ValueError: only one element tensors can be converted to Python scalars
#################################################
c = torch.tensor(x13)  # 但是x13无法转为tensor
'''

x1.shape =  (2, 3)
x2.shape =  (2, 3)
x3.shape =  (2, 2, 3)
torch.Size([1, 2, 2, 3])
--------------numpy初始化数据规律------------
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.int64'>
-----------------tensor初始化数据规律------------
<class 'torch.Tensor'>
<class 'torch.Tensor'>
tensor([1, 2])
<class 'torch.Tensor'>
可看出numpy创建数组，最外层类型就算array，最小单位还是int
但是用tensor创建tensor类型，从里到外所有数据类型都属于tensor
tensor([[1, 2],
        [2, 3]])
list中两个类型一样：array，array:
 [array([[1, 2, 3],
       [2, 3, 4]]), array([[ 6,  7,  8],
       [11, 12, 13]])]
list中两个类型不一样 array，tensor:
 [array([[ 6,  7,  8],
       [11, 12, 13]]), tensor([[1, 2, 3],
        [2, 3, 4]])]
list中两个类型一样 tensor，tensor:
 [tensor([[1, 2, 3],
        [2, 3, 4]]), tensor([[ 6,  7,  8],
        [11, 12, 13]])]


'\na = torch.tensor(x11)\nprint(a)\nprint(a[0])\nprint([a[0][0]])\nb = torch.tensor(x12)\nprint(b)   # a 和 b都成功被转换为了tensor，从里到外：ValueError: only one element tensors can be converted to Python scalars\n#################################################\nc = torch.tensor(x13)  # 但是x13无法转为tensor\n'

In [36]:
# cat() --- stack()
# outputs = torch.cat(inputs, dim=0) → Tensor
# 参数-inputs : 待连接的张量序列，可以是任意相同Tensor类型的python 序列
# 参数-dim : 选择的扩维, 必须在0到len(inputs[0])之间，沿着此维连接张量序列。

# print(torch.cat(x11, dim=0).shape)
# print(torch.cat(x12, dim=0).shape)  # 这两个都会报错，因为他要全是为tensor的
# 这个也不行：tensor(XXXXX)
# print(torch.cat(torch.tensor(x11), dim=0).shape)  

# 只有一种形式是可以的，[tensors]，最外层为list，里面全为tensors
# 以list形式一起送入cat，输出的结果和原来的tensor形状一致。维度不变，内容合并
print(x13)
print(len(x13))
print("原来的tensor形状为：", x13[0].size())
print("shape of x13：", [2,2,3])
# dim : 选择的扩维, 必须在0到len(inputs[0])之间，沿着此维连接张量序列。
print(torch.cat(x13, dim=0).shape)
print(torch.cat(x13, dim=0))
print(torch.cat(x13, dim=1).shape)
print(torch.cat(x13, dim=1))
print("dim=0,就是N个tensor合并，0维数值*N，比如这个例子0维上是2，2个tensors合并，2*2=4")
print("dim=1,就是N个tensor合并，1维数值*N，比如这个例子0维上是3，2个tensors合并，2*3=6")

#print(torch.cat(x13, dim=2).shape)

[tensor([[1, 2, 3],
        [2, 3, 4]]), tensor([[ 6,  7,  8],
        [11, 12, 13]])]
2
原来的tensor形状为： torch.Size([2, 3])
shape of x13： [2, 2, 3]
torch.Size([4, 3])
tensor([[ 1,  2,  3],
        [ 2,  3,  4],
        [ 6,  7,  8],
        [11, 12, 13]])
torch.Size([2, 6])
tensor([[ 1,  2,  3,  6,  7,  8],
        [ 2,  3,  4, 11, 12, 13]])
dim=0,就是N个tensor合并，0维数值*N，比如这个例子0维上是2，2个tensors合并，2*2=4
dim=1,就是N个tensor合并，1维数值*N，比如这个例子0维上是3，2个tensors合并，2*3=6


In [33]:
# stack操作后会在原来的基础上再增加一维
# 比如原来两个tensor的维度都是3维，经过stack后的结果为4维tensor

x111 = [torch.tensor(torch.rand(3,4)),torch.tensor(torch.rand(3,4))]
print(x111)
print("shape of x111：", [2,3,4])
print("原来的tensor形状为：", x111[0].size())
# dim : 选择的扩维, 必须在0到len(inputs[0])之间，沿着此维连接张量序列。
print(torch.stack(x111, dim=0).shape)
print(torch.stack(x111, dim=0))
print("--------")
print(torch.stack(x111, dim=1).shape)
print(torch.stack(x111, dim=1))
print("---------")
print(torch.stack(x111, dim=2).shape)
print(torch.stack(x111, dim=2))
print("---------")

[tensor([[0.0503, 0.1359, 0.0863, 0.5782],
        [0.4642, 0.7491, 0.0009, 0.0367],
        [0.7392, 0.4266, 0.7456, 0.5956]]), tensor([[0.8234, 0.6714, 0.8367, 0.8122],
        [0.5594, 0.1289, 0.3598, 0.1618],
        [0.0827, 0.0887, 0.6317, 0.6648]])]
shape of x111： [2, 3, 4]
原来的tensor形状为： torch.Size([3, 4])
torch.Size([2, 3, 4])
tensor([[[0.0503, 0.1359, 0.0863, 0.5782],
         [0.4642, 0.7491, 0.0009, 0.0367],
         [0.7392, 0.4266, 0.7456, 0.5956]],

        [[0.8234, 0.6714, 0.8367, 0.8122],
         [0.5594, 0.1289, 0.3598, 0.1618],
         [0.0827, 0.0887, 0.6317, 0.6648]]])
--------
torch.Size([3, 2, 4])
tensor([[[0.0503, 0.1359, 0.0863, 0.5782],
         [0.8234, 0.6714, 0.8367, 0.8122]],

        [[0.4642, 0.7491, 0.0009, 0.0367],
         [0.5594, 0.1289, 0.3598, 0.1618]],

        [[0.7392, 0.4266, 0.7456, 0.5956],
         [0.0827, 0.0887, 0.6317, 0.6648]]])
---------
torch.Size([3, 4, 2])
tensor([[[0.0503, 0.8234],
         [0.1359, 0.6714],
         [0.0863, 0.

/home/xiang/anaconda3/envs/py37/lib/python3.7/site-packages/ipykernel_launcher.py:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  after removing the cwd from sys.path.
