In [1]:
import torch
import torchvision


In [3]:
a = torch.randn(3,4)
print(a)
index = torch.tensor([0, 2])
print(torch.index_select(a, 1, index))

tensor([[ 1.6925,  0.6566, -2.1638,  1.8063],
        [-0.0592, -0.1012, -1.5423, -0.2400],
        [-1.6753, -1.0256, -0.7361,  1.2562]])
tensor([[ 1.6925, -2.1638],
        [-0.0592, -1.5423],
        [-1.6753, -0.7361]])


In [4]:
q = torch.linspace(0, 1, 3)
print(q)
qq = torch.tensor(2)
print(qq)
print(q+qq)

tensor([0.0000, 0.5000, 1.0000])
tensor(2)
tensor([2.0000, 2.5000, 3.0000])
