In [1]:
import torch
import torchvision


In [32]:
a = torch.randn(1,1,3,4)
print(a)
index = torch.tensor([0, 1, 2])
print(index)
index2 = torch.linspace(0,2,3)
print(index2)
print(torch.zeros(3,3))
z = torch.index_select(a[0][0], 1, index2)
print(z)
print(a)

tensor([[[[-0.3601,  0.4515,  0.6755, -0.6906],
          [ 0.1369,  0.9897, -0.8092, -0.0785],
          [ 0.6795,  0.0533, -0.2217, -0.0926]]]])
tensor([0, 1, 2])
tensor([0., 1., 2.])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


RuntimeError: Expected object of scalar type Long but got scalar type Float for argument #3 'index' in call to _th_index_select

In [4]:
q = torch.linspace(0, 1, 3)
print(q)
qq = torch.tensor(2)
print(qq)
print(q+qq)

tensor([0.0000, 0.5000, 1.0000])
tensor(2)
tensor([2.0000, 2.5000, 3.0000])


In [44]:
a = [-120., -119., -118., -117., -116., -115., -114., -113., -112., -111.,
        -110., -109., -108., -107., -106., -105., -104., -103., -102., -101.,
        -100.,  -99.,  -98.,  -97.,  -96.,  -95.,  -94.,  -93.,  -92.,  -91.,
         -90.,  -89.,  -88.,  -87.,  -86.,  -85.,  -84.,  -83.,  -82.,  -81.,
         -80.,  -79.,  -78.,  -77.,  -76.,  -75.,  -74.,  -73.,  -72.,  -71.,
         -70.,  -69.,  -68.,  -67.,  -66.,  -65.,  -64.,  -63.,  -62.,  -61.,
         -60.,  -59.,  -58.,  -57.,  -56.,  -55.,  -54.,  -53.,  -52.,  -51.,
         -50.,  -49.,  -48.,  -47.,  -46.,  -45.,  -44.,  -43.,  -42.,  -41.,
         -40.,  -39.,  -38.,  -37.,  -36.,  -35.,  -34.,  -33.,  -32.,  -31.,
         -30.,  -29.,  -28.,  -27.,  -26.,  -25.,  -24.,  -23.,  -22.,  -21.,
         -20.,  -19.,  -18.,  -17.,  -16.,  -15.,  -14.,  -13.,  -12.,  -11.,
         -10.,   -9.,   -8.,   -7.,   -6.,   -5.,   -4.,   -3.,   -2.,   -1.,
           0.,    1.,    2.,    3.,    4.,    5.,    6.,    7.,    8.,    9.,
          10.,   11.,   12.,   13.,   14.,   15.,   16.,   17.,   18.,   19.,
          20.,   21.,   22.,   23.,   24.,   25.,   26.,   27.,   28.,   29.,
          30.,   31.,   32.,   33.,   34.,   35.,   36.,   37.,   38.,   39.,
          40.,   41.,   42.,   43.,   44.,   45.,   46.,   47.,   48.,   49.,
          50.,   51.,   52.,   53.,   54.,   55.,   56.,   57.,   58.,   59.,
          60.,   61.,   62.,   63.,   64.,   65.,   66.,   67.,   68.,   69.,
          70.,   71.,   72.,   73.,   74.,   75.,   76.,   77.,   78.,   79.,
          80.,   81.,   82.,   83.,   84.,   85.,   86.,   87.,   88.,   89.,
          90.,   91.,   92.,   93.,   94.,   95.,   96.,   97.,   98.,   99.,
         100.,  101.,  102.,  103.,  104.,  105.,  106.,  107.,  108.,  109.,
         110.,  111.,  112.,  113.,  114.,  115.,  116.,  117.,  118.,  119.,
         120.]
for i in range(len(a)):
    a[i] = int(a[i])
print(a)

[-120, -119, -118, -117, -116, -115, -114, -113, -112, -111, -110, -109, -108, -107, -106, -105, -104, -103, -102, -101, -100, -99, -98, -97, -96, -95, -94, -93, -92, -91, -90, -89, -88, -87, -86, -85, -84, -83, -82, -81, -80, -79, -78, -77, -76, -75, -74, -73, -72, -71, -70, -69, -68, -67, -66, -65, -64, -63, -62, -61, -60, -59, -58, -57, -56, -55, -54, -53, -52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39, -38, -37, -36, -35, -34, -33, -32, -31, -30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 9

In [46]:
a = [0,1,2]
b = torch.randn(5,5)
print(b)
print(torch.index_select(b, 1, torch.tensor(a)))

tensor([[-0.6012, -1.6227,  1.8559, -0.1560, -0.4771],
        [ 2.4213, -0.3756,  0.5464, -0.3050, -0.1439],
        [-0.1902, -0.8990,  1.5535, -0.4535, -1.1975],
        [ 0.7534,  0.6907, -0.6147,  0.2393,  1.1008],
        [-0.6413, -0.5303,  0.0390,  0.9798, -0.7826]])
tensor([[-0.6012, -1.6227,  1.8559],
        [ 2.4213, -0.3756,  0.5464],
        [-0.1902, -0.8990,  1.5535],
        [ 0.7534,  0.6907, -0.6147],
        [-0.6413, -0.5303,  0.0390]])


In [53]:
a = torch.zeros(2,2)
b = torch.ones(2,2)
c = torch.randn(2,2)
print(torch.cat((torch.unsqueeze(a,0),torch.unsqueeze(b,0),torch.unsqueeze(c,0)),0))
x = torch.cat((torch.unsqueeze(a,0),torch.unsqueeze(b,0)),0)
print(x.size())
print(a)
print(b)

tensor([[[ 0.0000,  0.0000],
         [ 0.0000,  0.0000]],

        [[ 1.0000,  1.0000],
         [ 1.0000,  1.0000]],

        [[-0.2272,  0.3866],
         [ 0.2842,  0.2024]]])
torch.Size([2, 2, 2])
tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [50]:
c = torch.randn(2,2)
print(c)
print(c.size())
f = torch.unsqueeze(c,0)
print(f)
print(f.size())

tensor([[-0.4387, -1.0187],
        [ 0.0452, -1.4667]])
torch.Size([2, 2])
tensor([[[-0.4387, -1.0187],
         [ 0.0452, -1.4667]]])
torch.Size([1, 2, 2])


In [58]:
a = torch.zeros(1,1,1,1)
print(a)
c = torch.randn(2,2)
print(c)
d = torch.cat((a[0],c), 0)
print(d)

tensor([[[[0.]]]])
tensor([[ 0.0855,  1.4844],
        [-0.0633, -0.4544]])


RuntimeError: invalid argument 0: Tensors must have same number of dimensions: got 3 and 2 at /tmp/pip-req-build-ufslq_a9/aten/src/TH/generic/THTensor.cpp:603

In [64]:
a = torch.randn(1,1,2,2)
b = torch.randn(1,1,2,2)
c = torch.cat((a[0],b[0]), 0)
print(c.size())
d = torch.tensor([])
x = torch.index_select(a, 1, torch.tensor([0]))
print(x.size())

torch.Size([2, 2, 2])
torch.Size([1, 1, 2, 2])
