In [1]:
import torch
import torchvision


In [31]:
a = torch.randn(1,1,3,4)
print(a)
index = torch.tensor([0, 1, 2])
print(index)
index2 = torch.linspace(0,2,3, dtype=torch.LongTensor)
print(index2)
print(torch.zeros(3,3))
z = torch.index_select(a[0][0], 1, index2)
print(z)
print(a)

tensor([[[[-0.4276,  0.3577, -1.6963,  0.1028],
          [ 1.1718, -0.4200, -0.8100,  0.8659],
          [ 1.5940,  3.0699, -0.0156, -0.6506]]]])
tensor([0, 1, 2])


TypeError: linspace(): argument 'dtype' must be torch.dtype, not torch.tensortype

In [4]:
q = torch.linspace(0, 1, 3)
print(q)
qq = torch.tensor(2)
print(qq)
print(q+qq)

tensor([0.0000, 0.5000, 1.0000])
tensor(2)
tensor([2.0000, 2.5000, 3.0000])


In [ ]:
print(torch.linspace())