In [1]:
import torch
import torch.nn as nn
# 总结：adaptive和max一样的只是一个给kernel size一个给目标输出大小即可。

In [7]:
inputs = torch.randn(1, 1, 6,6)
print(inputs.size())
print(inputs)

torch.Size([1, 1, 6, 6])
tensor([[[[-0.5331,  0.7772, -0.1058, -1.0734, -0.5077, -1.2724],
          [-0.0352,  0.3657, -0.5381,  0.2923, -0.0721, -0.7214],
          [ 0.4208,  0.1269, -0.3822, -1.0592, -0.5083,  0.9973],
          [ 0.9719, -0.2112, -0.1413,  0.4572,  1.3210,  1.5157],
          [ 0.3063,  0.4386,  0.0284, -1.9653, -0.7246,  0.9775],
          [ 0.2678,  1.8638, -0.0339,  0.1334,  0.3856,  1.3407]]]])


In [8]:
pooling_max2d = nn.MaxPool2d(2)
output = pooling_max2d(inputs)   # 输入Maxpool的size必须为(bs, chs, w, h)
print(output.size())
print(output)

torch.Size([1, 1, 3, 3])
tensor([[[[ 0.7772,  0.2923, -0.0721],
          [ 0.9719,  0.4572,  1.5157],
          [ 1.8638,  0.1334,  1.3407]]]])


In [9]:
pooling_avg2d = nn.AvgPool2d(2)
output = pooling_avg2d(inputs)
print(output.size())
print(output)

torch.Size([1, 1, 3, 3])
tensor([[[[ 0.1436, -0.3562, -0.6434],
          [ 0.3271, -0.2814,  0.8314],
          [ 0.7191, -0.4593,  0.4948]]]])


In [10]:
ada_pooling_max2d = nn.AdaptiveMaxPool2d((3,3))
output = ada_pooling_max2d(inputs)
print(output.size())
print(output)

torch.Size([1, 1, 3, 3])
tensor([[[[ 0.7772,  0.2923, -0.0721],
          [ 0.9719,  0.4572,  1.5157],
          [ 1.8638,  0.1334,  1.3407]]]])


In [16]:
ada_pooling_avg2d = nn.AdaptiveAvgPool2d((3,3))
output = ada_pooling_avg2d(inputs)
print(output.size())
print(output)

torch.Size([1, 1, 3, 3])
tensor([[[[ 0.1436, -0.3562, -0.6434],
          [ 0.3271, -0.2814,  0.8314],
          [ 0.7191, -0.4593,  0.4948]]]])


In [13]:
import torch
import torch.nn as nn

a = nn.MaxPool2d((6,6),stride=5)
inputs = torch.randn(1,1,1200,1200)
print(a(inputs).size())

torch.Size([1, 1, 239, 239])
