In [1]:
import torch

In [5]:
# torch.Tensor有两个实例方法可以用来扩展某维的数据的尺寸，repeat()和expand()
"""
返回当前张量在某维扩展更大后的张量。扩展（expand）张量不会分配新的内存，
只是在存在的张量上创建一个新的视图(view)，一个大小(size)等于1的维度扩展到更大的尺寸。
"""

x = torch.tensor([1, 2, 3])
y = torch.randn(2, 1, 1, 4)

print(x.expand(2, 3))
print(x)
print(y)
print(y.expand(-1, 2, 3, -1))

tensor([[1, 2, 3],
        [1, 2, 3]])
tensor([1, 2, 3])
tensor([[[[-1.6047,  0.6197, -0.5595, -0.3511]]],


        [[[ 0.5251, -0.3712,  0.5103, -1.1937]]]])
tensor([[[[-1.6047,  0.6197, -0.5595, -0.3511],
          [-1.6047,  0.6197, -0.5595, -0.3511],
          [-1.6047,  0.6197, -0.5595, -0.3511]],

         [[-1.6047,  0.6197, -0.5595, -0.3511],
          [-1.6047,  0.6197, -0.5595, -0.3511],
          [-1.6047,  0.6197, -0.5595, -0.3511]]],


        [[[ 0.5251, -0.3712,  0.5103, -1.1937],
          [ 0.5251, -0.3712,  0.5103, -1.1937],
          [ 0.5251, -0.3712,  0.5103, -1.1937]],

         [[ 0.5251, -0.3712,  0.5103, -1.1937],
          [ 0.5251, -0.3712,  0.5103, -1.1937],
          [ 0.5251, -0.3712,  0.5103, -1.1937]]]])


In [6]:
# 沿着特定的维度重复这个张量，和expand()不同的是，这个函数拷贝张量的数据。

a = torch.tensor([1, 2, 3])
print(a.repeat(3, 2))
b = torch.randn(2, 3, 4)
print(b.repeat(2, 1, 3).shape)

tensor([[1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3]])
torch.Size([4, 3, 12])


In [7]:
# expand 只能扩展为1的维度
# 当维度为1时，repeat会分配新的内存存储增加的数据，expand不分配新内存。

import torch
import numpy as np
x = torch.tensor([1, 2, 3])
print(np.may_share_memory(x, x.expand(2,3))) #True
print(np.may_share_memory(x, x.repeat(2,3))) #False

True
False
