In [1]:
# 激活函数是什么，有什么用？不用激活函数可不可以？
# 不可以。激活函数的主要作用是提供网络的非线性建模能力。如果没有激活函数，那么该网络仅能够表达线性映射，此时即便有再多的隐藏层，其整个网络跟单层神经网络也是等价的。
# 因此也可以认为，只有加入了激活函数之后，深度神经网络才具备了分层的非线性映射学习能力。 

In [2]:
import torch
import torch.nn as nn

In [3]:
data = torch.randn(2)
print(data)

tensor([-2.3176, -0.1396])


In [11]:
# Relu = max(0, x)
relu = nn.ReLU(inplace=True)  # inplace=False(default)
print(relu(data))
# output = relu(data)
# print(output)
print(data)

tensor([0., 0.])
tensor([0., 0.])


In [16]:
# sigmoid = sigma(x) = 1/(1+exp(-x))
data = torch.rand(2)
sigmoid = nn.Sigmoid()
print(data)
print(sigmoid(data))

tensor([0.8656, 0.5539])
tensor([0.7038, 0.6350])


In [17]:
# tanh = tanh(x) = (exp(x)-exp(-x)) / (exp(x)+exp(-x))
data = torch.randn(3)
print(data)
tanh = nn.Tanh()
print(tanh(data))

tensor([ 0.3129, -1.1915, -0.0125])
tensor([ 0.3031, -0.8311, -0.0125])


In [30]:
# LeakyReLU = x if x>=0; else negative_slope*x
# LeakyReLU = max(0, x) + negative_slope * min(0, x)
data = torch.tensor([-1., 0., 1.])
print(data)
leaky_relu = nn.LeakyReLU()   # 注意要用浮点数字
print(leaky_relu(data))

tensor([-1.,  0.,  1.])
tensor([-0.0100,  0.0000,  1.0000])


In [35]:
# PReLU = max(0, x) + a*min(0, x)
data = torch.tensor([-2., 0., 2.])
print(data)
prelu = nn.PReLU(init=0.1)
print(prelu(data))

tensor([-2.,  0.,  2.])
tensor([-0.2000,  0.0000,  2.0000], grad_fn=<PreluBackward>)


In [41]:
# RReLU = x if x>=0; else ax
data = torch.tensor([-2., 0., 2.])
print(data)
rrelu = nn.RReLU(lower=0.1, upper=0.2)  
# 在lower和upper之间随机取的，若想取一个值，lower=upper即可a
print(rrelu(data))

tensor([-2.,  0.,  2.])
tensor([-0.2156,  0.0000,  2.0000])


In [42]:
# ELU = max(0, x) + min(0, alpha*(exp(x)-1))
data = torch.tensor([-2., 0., 2.])
print(data)
elu = nn.ELU()
print(data)

tensor([-2.,  0.,  2.])
tensor([-2.,  0.,  2.])
