In [2]:
import torch
import torch.nn as nn

In [3]:
# 在图片单标签分类时，输入m张图片，输出一个m*N的Tensor，其中N是分类个数。
# 比如输入3张图片，分三类，最后的输出是一个3*3的Tensor

input = torch.randn(3,3)
print(input)
# 一二三行是第1第2第3张图片的输出结果！
# 假设顺序为：猫，狗，猪。可以看出三个分别应该是：猫，猪，猫

tensor([[ 0.3505, -0.2069, -0.6223],
        [-0.1869, -0.7892,  0.2590],
        [ 0.8319,  0.5871, -0.2757]])


In [4]:
sm = nn.Softmax(dim=1)  # dim =1，按行来归一化，每行的和为1
print(sm(input))  # 三个结果对应的类别海斯猫狗狗
print("----log_softmax----")
print(torch.log(sm(input)))

tensor([[0.5126, 0.2936, 0.1938],
        [0.3216, 0.1761, 0.5023],
        [0.4732, 0.3705, 0.1563]])
----log_softmax----
tensor([[-0.6682, -1.2256, -1.6410],
        [-1.1344, -1.7367, -0.6886],
        [-0.7482, -0.9930, -1.8558]])


In [7]:
print("----------NLLLoss----------")
print("---把上面输出与真实label对应的那个值拿出来，再去掉符号负号再求均值---")
target = torch.tensor([0, 2, 1])  # 第一个：猫，第二个：猪，第三个：狗
# 明显猜对了两个
output = (-torch.log(sm(input))[0][0]-torch.log(sm(input))[1][2]-torch.log(sm(input))[2][1])/3
print(output)

----------NLLLoss----------
---把上面输出与真实label对应的那个值拿出来，再去掉符号负号再求均值---
tensor(0.7832)


In [8]:
# CrossEntropyLoss 检验
crossentropuloss = nn.CrossEntropyLoss()
print("确保input没有改变,怕inplace操作：\n", input)
print(crossentropuloss(input, target))

确保input没有改变,怕inplace操作：
 tensor([[ 0.3505, -0.2069, -0.6223],
        [-0.1869, -0.7892,  0.2590],
        [ 0.8319,  0.5871, -0.2757]])
tensor(0.7832)
