In [14]:
import torch

In [32]:
x = torch.rand(1,1,2,3)
y = torch.rand(7)  # 均匀分布
print(y)

tensor([0.4716, 0.6204, 0.9053, 0.3768, 0.0322, 0.8834, 0.3157])


In [33]:
print(x.size())
print(x)
x = x.squeeze()
print(x)
x = x.unsqueeze(dim=0)
print(x.size())
print(x)
x = x.unsqueeze(dim=0)
print(x.size())
print(x)

torch.Size([1, 1, 2, 3])
tensor([[[[0.2907, 0.7564, 0.5959],
          [0.0264, 0.4846, 0.8854]]]])
tensor([[0.2907, 0.7564, 0.5959],
        [0.0264, 0.4846, 0.8854]])
torch.Size([1, 2, 3])
tensor([[[0.2907, 0.7564, 0.5959],
         [0.0264, 0.4846, 0.8854]]])
torch.Size([1, 1, 2, 3])
tensor([[[[0.2907, 0.7564, 0.5959],
          [0.0264, 0.4846, 0.8854]]]])


In [37]:
# view函数相当于resize的功能，将原来的tensor变换成指的维度
# torch.view(参数a,参数b,.....)，其中参数a=3,参数b=2决定了将一维的tt1重构成3*2维的张量。
# 有时候会出现torch.view(-1)或者torch.view(参数a,-1)这种情况。则-1参数是需要估算的。

print(x.view(x.size(0), -1))
print(x.view(-1))
print(x.view(1,-1))
print(x.view(2,-1))
print("----------------------")
print(y.view(-1))
print(y.view(7))
print(y.view(7,-1))

print(y.view(2,3))
print(y)

tensor([[0.2907, 0.7564, 0.5959, 0.0264, 0.4846, 0.8854]])
tensor([0.2907, 0.7564, 0.5959, 0.0264, 0.4846, 0.8854])
tensor([[0.2907, 0.7564, 0.5959, 0.0264, 0.4846, 0.8854]])
tensor([[0.2907, 0.7564, 0.5959],
        [0.0264, 0.4846, 0.8854]])
----------------------
tensor([0.4716, 0.6204, 0.9053, 0.3768, 0.0322, 0.8834, 0.3157])
tensor([0.4716, 0.6204, 0.9053, 0.3768, 0.0322, 0.8834, 0.3157])
tensor([[0.4716],
        [0.6204],
        [0.9053],
        [0.3768],
        [0.0322],
        [0.8834],
        [0.3157]])


RuntimeError: shape '[2, 3]' is invalid for input of size 7