In [26]:
import torch
import torch.nn as nn
import torch.functional as F
import torch.utils.data as Data
import matplotlib.pyplot as plt

In [27]:
EPOCH = 1
BATCH_SIZE = 50
LR = 0.001
x = 
y = 

SyntaxError: invalid syntax (2995480091.py, line 4)

In [24]:
torch_dataset = Data.TensorDataset(x, y)
loader = Data.DataLoader(dataset=torch_dataset, batch_size=BATCH_SIZE,
                        shuffle=True, num_workers=2,)

NameError: name 'Data' is not defined

In [19]:
class NN(nn.Module):
    def __init__(self):
        super(NN, self).__init__()
        self.conv1 = nn.Sequential(
            nn.Conv2d(
                in_channels = 1,
                out_channels = 16,
                kernel_size = 5,
                stride = 1,
                padding = 2,  
            ),   
            nn.ReLU(),  
            nn.MaxPool2d(kernel_size=2),   
        )
        
        self.conv2 = nn.Sequential( 
            nn.Conv2d(16, 32, 5, 1, 2),  
            nn.ReLU(),  
            nn.MaxPool2d(2),  
        )
        
        self.out = nn.Linear(32 * 7 * 7, 10)
        
    def forward(self, x):
        x = self.conv1(x)
        x = self.conv2(x)   
        x = x.view(x.size(0), -1)   
        output  = self.out(x)
        return output, x

In [20]:
strategy_nn = NN()

# SGD
optimizer = torch.optim.Adam(strategy_nn.parameters(), lr=LR)   # optimize all nn parameters
loss_func = nn.CrossEntropyLoss()                       # the target label is not one-hotted

In [21]:
from matplotlib import cm
try: from sklearn.manifold import TSNE; HAS_SK = True
except: HAS_SK = False; print('Please install sklearn for layer visualization')
def plot_with_labels(lowDWeights, labels):
    plt.cla()
    X, Y = lowDWeights[:, 0], lowDWeights[:, 1]
    for x, y, s in zip(X, Y, labels):
        c = cm.rainbow(int(255 * s / 9)); plt.text(x, y, s, backgroundcolor=c, fontsize=9)
    plt.xlim(X.min(), X.max()); plt.ylim(Y.min(), Y.max()); plt.title('Visualize last layer'); plt.show(); plt.pause(0.01)

In [25]:
plt.ion()
# training and testing
for epoch in range(EPOCH):
    for step, (b_x, b_y) in enumerate(train_loader):   # gives batch data, normalize x when iterate train_loader

        output = cnn(b_x)[0]              
        loss = loss_func(output, b_y)   
        optimizer.zero_grad()           # clear gradients for this training step
        loss.backward()                 # backpropagation, compute gradients
        optimizer.step()                # apply gradients

        if step % 50 == 0:
            test_output, last_layer = cnn(test_x)
            pred_y = torch.max(test_output, 1)[1].data.numpy()
            accuracy = float((pred_y == test_y.data.numpy()).astype(int).sum()) / float(test_y.size(0))
            print('Epoch: ', epoch, '| train loss: %.4f' % loss.data.numpy(), '| test accuracy: %.2f' % accuracy)
            if HAS_SK:
                # Visualization of trained flatten layer (T-SNE)
                tsne = TSNE(perplexity=30, n_components=2, init='pca', n_iter=5000)
                plot_only = 500
                low_dim_embs = tsne.fit_transform(last_layer.data.numpy()[:plot_only, :])
                labels = test_y.numpy()[:plot_only]
                plot_with_labels(low_dim_embs, labels)
plt.ioff()

NameError: name 'plt' is not defined

In [28]:
test_output, _ = cnn(test_x[:10])
pred_y = torch.max(test_output, 1)[1].data.numpy()
print(pred_y, 'prediction number')
print(test_y[:10].numpy(), 'real number')

NameError: name 'cnn' is not defined

In [32]:
a = {}
len(a)
b = [{}]
len(b)

1

In [11]:
import torch
a = torch.randint(low=1, high=10, size=(1,10))
print(a)
b = torch.clamp(a, 3, 6)
print(b)
print(torch.clamp(a, min=4))
print(torch.clamp(a, max=6))
print("-----很奇怪换个位置为啥会这样-----")
print(torch.clamp(a, 6, 3))

tensor([[5, 8, 3, 7, 2, 5, 1, 4, 2, 6]])
tensor([[5, 6, 3, 6, 3, 5, 3, 4, 3, 6]])
tensor([[5, 8, 4, 7, 4, 5, 4, 4, 4, 6]])
tensor([[5, 6, 3, 6, 2, 5, 1, 4, 2, 6]])
-----很奇怪换个位置为啥会这样-----
tensor([[3, 3, 3, 3, 3, 3, 3, 3, 6, 3]])
