In [1]:
import numpy as np
import pandas as pd

In [7]:
name = ['a', 'b', 'c']
index = [0, 1, 2]
data = np.array([[1., 0., 1.],
                 [0., 1., 1.],
                 [1., 0., 1.]])
print(data)

[[1. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]]


In [58]:
dataset = pd.DataFrame(data=data, index=index, columns=name)
print(dataset)

     a    b    c
0  1.0  0.0  1.0
1  0.0  1.0  1.0
2  1.0  0.0  1.0


In [64]:
output = []
for item in dataset.index:
    
    # values of rows
    a = np.array(dataset.loc[item])
    
    # get nonzero position
    nonzero_pos = np.nonzero(a)[0]
    
    # tmp var for sum of each row
    tmp_row = 0
    
    for position in nonzero_pos:
        column_name = name[position]
        tmp_row += np.sum(dataset[column_name])

    # print("index为%d: %d"%(item,tmp_row))
    output.append(tmp_row)

output_ = pd.DataFrame(data=output, index=index)
print(output_)

     0
0  5.0
1  4.0
2  5.0
